version: '3'

services:
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      PGPASSWORD: "${DB_PASSWORD:-ChangeMe}"
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    volumes:
      - "pgsql:/var/lib/postgresql/data"

volumes:
  pgsql:
    driver: local
